[build]
  publish = "public"
  functions = "netlify/functions"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

# Pages
[[redirects]]
  from = "/search"
  to = "/search.html"
  status = 200

[[redirects]]
  from = "/artist"
  to = "/artist.html"
  status = 200

[[redirects]]
  from = "/saved"
  to = "/saved.html"
  status = 200

[[redirects]]
  from = "/profile"
  to = "/profile.html"
  status = 200

[[redirects]]
  from = "/friends"
  to = "/friends.html"
  status = 200

[[redirects]]
  from = "/auth/callback"
  to = "/auth/callback.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"